DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID  Integer  NOT NULL,
    JP_LEVEL_ID	 Integer     NOT NULL,
	DEPARTMENT_ID  Integer        NOT NULL,
	POSITION_ID  Integer  NOT NULL,
	EMPLOYEE_NAME VARCHAR(100) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	GENDER  VARCHAR(10)  NOT NULL,
	JOIN_DATE DATE NOT NULL,
	MATERIAL_STATUS VARCHAR(10) NOT NULL,
	EMAIL VARCHAR(300) NOT NULL,
	PHONE_NUMBER VARCHAR(11)  NOT NULL,
	START_TIME TIMESTAMP WITHOUT TIME ZONE,
	END_TIME TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT EMP_PK1 PRIMARY KEY(EMPLOYEE_ID),
       FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT,
       FOREIGN KEY (JP_LEVEL_ID) REFERENCES JAPANESE_LEVEL,
	   FOREIGN KEY (POSITION_ID) REFERENCES POSITION
)
;
COMMIT;